# Generated by Django 6.0.5 on 2026-05-11 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('general', 'General Event'), ('career_fair', 'Career Fair'), ('concert', 'Concert'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('hackathon', 'Hackathon')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('ticket_limit', models.PositiveIntegerField()),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='event_banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'eventify_events',
                'ordering': ['-date_time'],
            },
        ),
    ]
